### PR TITLE
Rewrite element to custom elements v1 syntax and remove Polymer dependency

### PR DESCRIPTION
**Pull request by TimvdLippe**
Rewrote this element to the new custom elements v1 syntax. Do not merge yet.

### CODE REVIEW

**Comment by martijnjanssen** [comment]
Could you also update the readme accordingly since the entire polymer dependency has now been removed?

**Comment by TimvdLippe** [comment]
@martijnjanssen shall we do this as well?

**Comment by martijnjanssen** [comment]
Yup, I don't know why we did not finish this one.

**Comment by TimvdLippe** [comment]
image
Working! Merging :tada:

**Pull request merged**
